@startuml
scale 3508 width

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/Client.puml
!includeurl AWSPuml/General/TraditionalServer.puml
!includeurl AWSPuml/NetworkingAndContentDelivery/VPCRouter.puml
!includeurl AWSPuml/InternetOfThings/IoTCamera.puml

skinparam rectangle {
  BackgroundColor Transparent
  BorderColor Transparent
  shadowing false
}

rectangle "<color:#000000><$Client></color>\nAlice\n192.168.0.115/24" as alice
rectangle "<color:#000000><$Client></color>\nEve\n192.168.0.168/24" as eve
rectangle "<color:#000000><$TraditionalServer></color>\nBob\n192.168.0.171/24" as bob
rectangle "<color:#000000><$IoTCamera></color>\nSecurity Camera\n192.168.0.178/24" as pi
rectangle "<color:#000000><$VPCRouter></color>\nRouter\n192.168.0.1" as router

alice -- router
eve -- router
bob -- router
pi -- router

@enduml
